module.exports = {
    MONGODB_URL: process.env.MONGODB_URL,
    SESSION_SECRET: process.env.SESSION_SECRET,
    SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
    EMAIL_SERVICE_NAME: process.env.EMAIL_SERVICE_NAME,
    EMAIL_SERVICE_USER_NAME: process.env.EMAIL_SERVICE_USER_NAME,
    EMAIL_SERVICE_USER_PASS: process.env.EMAIL_SERVICE_USER_PASS,
    EMAIL_FROM: process.env.EMAIL_FROM,
    BASE_URL: process.env.BASE_URL
};